[build-system]
requires = [
    "setuptools>=68.0.0",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp310* cp311* cp312* cp313* pp310*"
free-threaded-support = true
before-build = "sudo apt update|sudo apt install gcc-10 g++-10"