[build-system]
requires = [
    "setuptools>=68.0.0",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp312* cp313* pp310*"
free-threaded-support = true

[tool.cibuildwheel.linux]
before-build = '''export CC=gcc-12 && export CXX=g++-12'''